import sys
thing = "die now"
print("    -----_______|________-----")
print("                |             ")
print("                |             ")
print("         _ _|  |              ")
print("           |   |              ")
print("     |_____|  |               ")
print("     |     |  |               ")
print("     | . . | |                ")
print("     |     | |                ")
print("    ||     ||                 ")
print("   | |     |                  ")
print("  |  |_____|                  ")
print("     |     |                  ")
print("  __________________________  ")
print(" |                          | ")
print(" | Yahahaha you found me    | ")
print(" |__________________________| ")
sys.exit(thing)
